---
- name: Provision Autopilot GKE cluster with Terraform
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Install Terraform
      apt:
        name: terraform
        state: present

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: terraform

    - name: Create Cluster
      command: terraform apply -auto-approve -var="project_id=crewnetics-dev" -var="credential=crewnetics-dev-352099b311f4.json" -var="region_name=us-central1" -var="environment=test" -var="autopilot=true" 
      args:
        chdir: terraform
