---
- name: Provision Autopilot GKE cluster with Terraform
  hosts: localhost
  gather_facts: false
  vars_files:
  - ansible.vars.yml
  
  tasks:
    - name: Install Terraform
      apt:
        name: terraform
        state: present

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: terraform

    - name: Create Cluster
      command: terraform apply -auto-approve -var="project_id={{ project_id }}" -var="credential={{ credential }}" -var="region_name={{ region_name }}" -var="cluster_name={{ cluster_name }}" -var="autopilot={{ autopilot }}" 
      args:
        chdir: terraform
